[tool.poetry]
name = "entangled-cli"
version = "2.1.0"
description = "Literate Programming toolbox"
repository = "https://github.com/entangled/entangled.py"
homepage = "https://entangled.github.io/"
authors = ["Johan Hidding <j.hidding@esciencecenter.nl>"]
license = "Apache 2"
readme = "README.md"
packages = [{ include = "entangled" }]

[tool.poetry.dependencies]
python = "^3.11"
mawk = "^0.1.4"          # use mawk as line parsing engine
watchdog = "^3.0.0"      # file watching
filelock = "^3.12.0"     # file lock for json db
argh = "^0.30"           # easy argument parsing
rich = "^13.3.5"         # colourful output
tomlkit = "^0.12.1"      # read/write toml files
copier = "^9"            # project templates
brei = "^0.2.3"          # build system
rich-argparse = "^1.4.0" # colourful help messages
pexpect = "^4.9.0"
pyyaml = "^6.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
mypy = "^1.3.0"
black = "^23.3.0"
pytest-cov = "^4.0.0"
mkdocs = "^1.4.3"
mkdocs-material = "^9.1.13"
mkdocstrings = { extras = ["python"], version = "^0.21.2" }
twine = "^4.0.2"
pytest-asyncio = "^0.21.1"
ruff = "^0.4.4"
types-pyyaml = "^6.0.12.20240311"
types-pygments = "^2.18.0.20240506"
types-colorama = "^0.4.15.20240311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.mypy]
packages = ["entangled"]

[tool.poetry.scripts]
entangled = "entangled.main:cli"
